subject=["c","c++","java","python","html"]
print(subject)
print(subject[2:])

print("java" in subject)
print(subject * 3)
print(len(subject))
subject.append("toc")
print(subject)
subject.insert(2,"cpu")
print(subject)
subject.remove("c++")
print(subject)
subject.sort()
print(subject)
subject.pop()
print(subject)
subject2=subject.copy()
print(subject)
position=subject.index()
print(position)
